# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
np.__version__

'1.20.1'

2) Создать нулевой вектор размера 10

In [2]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [3]:
a = np.full(7, 7)
a

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
a = 2*np.arange(5, 51)
a

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
a = np.random.permutation(20)
a = a[::-1]

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [6]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [7]:
a = np.eye(4 , k=1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [8]:
a = np.diagflat([[1, 2], [3, 4]]) + np.full(4, 7) - 7*np.eye(4)
a

array([[1., 7., 7., 7.],
       [7., 2., 7., 7.],
       [7., 7., 3., 7.],
       [7., 7., 7., 4.]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [9]:
a = np.full((5,5), np.arange(5))
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [10]:
a = np.full((10, 10), np.random.rand(10, 10))
for i in range(10):
    for j in range(10):
        a[i][j] -= np.average(a[i])

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [11]:
a = np.full((10, 10), np.random.rand(10, 10))
a = np.transpose(a)
for i in range(10):
    for j in range(10):
        a[i][j] -= np.median(a[i])
a = np.transpose(a)

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [12]:
a = np.full((5, 5), np.random.rand(5, 5))
a = np.c_[a, np.array([np.max(a[i]) for i in range(5)]), np.array([np.min(a[i]) for i in range(5)])]

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [24]:
a = np.arange(1, 51)
odd = a[::2].reshape(5,5)
even = a[1::2].reshape(5,5)
b = odd*even
inv = np.linalg.inv(b)

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [25]:
a = np.zeros((8, 8))
for i in range(-3, 3):
    a += np.eye(8, k = 2*i)